plugins {
    id 'java-library'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
    id 'me.modmuss50.mod-publish-plugin' version '2.1.1'
    id 'com.diffplug.spotless' version '8.10.3'
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}

apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/maven.gradle'
apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/publishing-2.gradle'
apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/utils.gradle'
apply from: 'https://raw.githubusercontent.com/FTBTeam/mods-meta/v1/gradle/changelog.gradle'

version = createModVersion(project)
group = project.maven_group

base {
    archivesName = archives_base_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

neoForge {
    version = project.neoforge_version

    runs {
        configureEach {
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
        }

        server {
            server()
            programArguments.add('--nogui')
        }

        clientData {
            clientData()
            programArguments.addAll('--mod', project.mod_id, '--all',
                '--output', file('src/generated/resources/').absolutePath,
                '--existing', file('src/main/resources/').absolutePath)
        }
    }

    mods {
        "${project.mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    mavenCentral()
    commonMavenRepos(repositories)

    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

configurations {
    productiveBeesArtifact
}

dependencies {
    compileOnly("maven.modrinth:geckolib:${geckolib_modrinth_id}")
    runtimeOnly("maven.modrinth:geckolib:${geckolib_modrinth_id}")
    compileOnly("maven.modrinth:jade:${jade_modrinth_id}")
    runtimeOnly("maven.modrinth:jade:${jade_modrinth_id}")
    compileOnly("curse.maven:ae2-223794:${ae2_curse_file_id}")
    compileOnly("curse.maven:sophisticatedcore-618298:${sophisticatedcore_curse_file_id}")
    compileOnly("curse.maven:sophisticatedstorage-619320:${sophisticatedstorage_curse_file_id}")
    compileOnly("curse.maven:sophisticatedbackpacks-422301:${sophisticatedbackpacks_curse_file_id}")
    compileOnly("curse.maven:neovitae-1404763:${neovitae_curse_file_id}")
    compileOnly("curse.maven:occultism-361026:${occultism_curse_file_id}")
    compileOnly("curse.maven:thaumaturge-1628024:${thaumaturge_curse_file_id}")
    compileOnly("curse.maven:oritech-1030830:${oritech_curse_file_id}")
    compileOnly("curse.maven:ftbic-539097:${ftbic_curse_file_id}")
    compileOnly("curse.maven:productivebees-377897:${productivebees_curse_file_id}")
    productiveBeesArtifact("curse.maven:productivebees-377897:${productivebees_curse_file_id}")
    compileOnly files(provider {
        zipTree(configurations.productiveBeesArtifact.singleFile).matching {
            include 'META-INF/jarjar/productivelib-*.jar'
        }.files
    })
    compileOnly("curse.maven:irons-artifice-1650193:${irons_artifice_curse_file_id}")
    compileOnly("curse.maven:justdirefuels-1554863:${justdirefuels_curse_file_id}")
    compileOnly("curse.maven:agritechevolved-1287394:${agritechevolved_curse_file_id}")
    compileOnly("curse.maven:apotheosis-313970:${apotheosis_curse_file_id}")
    compileOnly("curse.maven:placebo-283644:${placebo_curse_file_id}")
}

tasks.withType(ProcessResources).configureEach {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    var replaceProperties = [
            mod_id                 : mod_id,
            version                : version,
            minecraft_version      : minecraft_version,
            neoforge_loader_version: neoforge_loader_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version       : neoforge_version,
            neoforge_version_range : neoforge_version_range,
            geckolib_version_range : geckolib_version_range,
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

createMavenPublishingBlock(project)

publishMods {
    file = jar.archiveFile

    dryRun = providers.environmentVariable("CURSEFORGE_KEY").getOrNull() == null || providers.environmentVariable("SKIP_CURSEFORGE").getOrNull() != null
    changelog = createChangelog(project)
    version = project.version
    type = createReleaseType(project)

    modLoaders.add("neoforge")

    curseforge {
        projectId = project.curseforge_id
        projectSlug = "ftb-armory"
        accessToken = providers.environmentVariable("CURSEFORGE_KEY")
        minecraftVersions.add(minecraft_version)
        client = true
        server = true
        requires("geckolib")
    }
}

spotless {
    java {
        target 'src/*/java/**/*.java'
        palantirJavaFormat()
        importOrder()
        removeUnusedImports()
        trimTrailingWhitespace()
        endWithNewline()
    }
}
