# Gradle
org.gradle.jvmargs=-Xmx4G

# Mod settings
mod_version=1

mod_id=ftbarmory
maven_group=dev.ftb.mods
archives_base_name=ftb-armory

# Minecraft version
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)

# NeoForge versions
neoforge_version=26.1.2.109
neoforge_version_range=[26.1.2.73,27)
neoforge_loader_version=11

# Dependencies
geckolib_version=5.5.2
geckolib_version_range=[5.5.2,)
geckolib_modrinth_id=xfVfPcoC

# CurseForge
curseforge_id=1722660
curseforge_type=beta
