modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
license = "All Rights Reserved"

[[mixins]]
config = "ftbarmory.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "FTB Armory"
authors = "FTB Team"
description = '''
FTB Armory - post-netherite metals (Adamantite, Aeternium and Aurichalcum) with their ores, materials, tools, weapons and armor.
'''

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "geckolib"
type = "required"
versionRange = "${geckolib_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${mod_id}]]
modId = "thaumaturge"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "arsmagicalegacy"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "witchery"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "occultism"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neovitae"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "enderio"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ltxi"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "hostilenetworks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "colossal_reactors"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "powah"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ironjetpacks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ironfurnaces"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sophisticatedstorage"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "sophisticatedbackpacks"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ae2"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "apothic_spawners"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "apothic_enchanting"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "apotheosis"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "oritech"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "ftbic"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "productivebees"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "justdirefuels"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "agritechevolved"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "irons_artifice"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "modonomicon"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"
